### ISSUE TITLE
Add Support for SysML

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#138]
The Systems Modeling Language (SysML) is a general-purpose modeling language for systems engineering applications. UML is focused on designing software, SysML allows you to design a complex system like an Autonomous Vehicle, Mars Rover, or Medical Device. It allows you to connect the behavior, structure, and requirements of a system through multiple abstraction levels. This is why I am interested in Gaphor, having an open source and simple modeling tool would be a huge boost to teaching engineers how to design complex systems. SysML is a subset and extension of UML. 

## High Level Changes
There are changes to the diagrams, including adding additional diagrams:
1. Requirements Diagram
1. Parametric Diagram
- This is a low impact for Gaphor since we only have 1 diagram type.

### Structure
Object, Profile, Deployment, and Component diagrams are removed.
- For Gaphor, the Component and Profile portions of the Palette could be hidden / removed

### Behavior
Communication, Interaction Overview, and Timing diagrams are removed. Protocol state machines are removed (behavior state machines remain).
- For Gaphor, what we support for Interactions could be renamed Sequence

## High Priority Changes

1. Blocks (Class)
- Associations have no arrowheads on both ends, which is the default we display them as well

2. Internal Blocks
- 4 properties of Blocks, but only parts, references are high priority
- Proxy ports and flow specifications

3. Requirement (Class)
- DeriveReqt, Verify, Satisfy (Trace)

4. Change Palettes 
- Hide Classes, Components, and Profiles Palettes
- Rename Interactions to Sequence
- Add Block, Internal Block, and Requirements Palettes

## Medium Priority Changes
1. Blocks – value properties and constraint properties
1. Allocation
1. Do we need a way to make an Activity (defining reusable behavior of an Action)?

## Low Priority Changes:
1. Parametric Diagram - I'm not a big fan of the usefulness of modeling parametrics
2. Model Elements support
- Conform (dependency)
- View (package)
- Viewpoint (Class)
- Rationale and Problem (Comments)
3. ValueType
4. QuantityKind / Unit
5. Block value properties and constraint properties
6. Activity extensions
- Control as Data
- Continuous Systems
- Probability
7. Copy (Trace)
8. Constraint Blocks

### I'm submitting a...
- [ ] Bug report  
- [X] Feature request
- [ ] Documentation issue or request

**Comment by danyeaw** [comment]
I have created a new branch called sysml-support. In it I have created two profiles:
1. `gaphor/profiles/sysml.gaphor` - A profile based on the SysML 1.6 spec
2. `gaphor/profiles/safety-reliability.gaphor` - A profile based on the Safety and Reliability Analysis spec. The spec is in final draft and will be released by the OMG soon.

The facilities that @amolenaar built in to the tool already to handle profiles and extensions are really good, I would say that 95% of the profiles are complete based on the specs.

As far as updating the tool to allow modeling of these profiles, here are some things to consider:
1. Users may want to mix SysML and UML in the same model. I don't think we want to limit this, so I'm not sure that reconfiguring Gaphor automatically based on the model open would make sense. 
1. SysML will need different tools in the Tool Palette, and different tool headings than UML. The Safety and Reliability Analysis profile is an extension of SysML, and we'll want to customize the tool palette for this as well, so instead of just getting an option for a Requirement in the palette, you can get a Technical Safety Requirement. I think the most straightforward way to implement this would be to create multiple tool palettes that can be selected by the user based on what they are working on.
1. We could also automatically update the tool palette and show only the tools applicable to the diagram type open, but this would require implementing multiple diagram types.
1. In UML, there is two main compartments in the Editor side panel: Attributes and Operations. SysML has Parts, References, Values, Constraints, and Properties. Since what is displayed in the Editor is already customized to what is selected on the diagram, my assumption is that we can change what is displayed for SysML elements as needed.
1. The SysML Internal Block Diagram, and the Parametric Diagram, which is a type of IBD, are both extended from the UML Composite Structure Diagram. This diagram is unique because we only currently support the Component Diagram with UML. To support the SysML IBD may require more work to build the Tool Palette and the diagram representation. The CSD / IBD allow for showing the instance or usage ("part") of the structure instead of the defining Class or Block itself.

I would be glad to have any feedback at this point on thoughts on how we should support this. I will start trying to mock up the changes needed to the GUI.

**Comment by amolenaar** [comment]
1. True
2. I think multiple tool boxes is probably the best option. It simply does not fit in one.
3. I'm not sure if we want to type the diagrams. It may be useful in that we can tie the toolbox to the diagram (which it already is), but it conflicts with _1._.
4. It can be done by adding new Property pages to Gaphor.
5. I'm not sure what you mean by this.

How generic do we want to make this? It's probably good enough to code it in to Gaphor directly, right? This is the easiest way to get the tool boxes and property pages in.

**Comment by danyeaw** [comment]
I agree that coding this in would be fine. I was assuming that Profile Selection (UML, SysML, BPMN, etc) would be a separate service, does that make sense to you as well based on the software architecture?

Part 5 was just a statement that we will need to support a new tool palette type in UML called a Component Structure that isn't currently supported.

**Comment by danyeaw** [comment]
Should we put which profile to select as radio actions on the hamburger menu or somewhere else like in the preferences?

![Screenshot from 2020-01-09 21-56-31](https://user-images.githubusercontent.com/10014976/72122271-5b80cf00-332b-11ea-8aba-e42290e12efa.png)

**Comment by danyeaw** [comment]
After talking to you on Gitter, how about:
![Screenshot from 2020-01-11 15-04-15](https://user-images.githubusercontent.com/10014976/72210097-23d96a80-3484-11ea-92d6-664c12553a2e.png)
![Screenshot from 2020-01-11 15-06-14](https://user-images.githubusercontent.com/10014976/72210098-26d45b00-3484-11ea-8a81-fe8396ce5814.png)

**Comment by amolenaar** [comment]
I like this..Maybe there should be a little spacer somewhere.

Does it make more sense to put the new diagram button on the right side of the profile chooser?

Maybe we should provide a little more guidance to the user? They have to know about UML profiles. Is it an advanced feature? Would you expect the profile to be set once per model or can it change per diagram? 

I would expect it to become unclear to a user when they can choose the profile from the toolbox itself. What do you think?

**Comment by danyeaw** [comment]
I'm not sure, this is what it looks like if I move the new diagram button to the right:
![Screenshot from 2020-01-12 21-39-16](https://user-images.githubusercontent.com/10014976/72230511-02f83e80-3584-11ea-8541-4ec1181fda7b.png)

I would expect that someone would only pick UML or SysML for a complete model. For the Safety & Reliability Analysis profile, they may be switching back and forth between that and the SysML profile in the same model, and even in the same diagram.

I think making it prominent like this on the header bar is good.

**Comment by danyeaw** [comment]
Breaking the resolution of this issue in to tasks, as we discussed on Gitter:

-  [X] Create SysML and Safety gaphor models - #292 
-  [X] Add profile selection combo box to header, make the current profile a property, make a separate toolbox for each profile
- [ ] Create a C4 gaphor model
- [ ] Create a new UMLModelProvider service
- [ ] Create a new core gaphor model based on at least a subset of the UML kernel
- [ ] Abstract gen_uml and build_uml so that we can load and generate any type of profile
- [ ] Create a core model library. Move the core portions of the diagram and toolbox, put the UML specific portions with the UML service
- [ ] Create SysMLModelProvider service. Implement a SysML diagram type.
- [ ] Create SafetyModelProvider service. Implement a Safety diagram type.
- [ ] Create a C4ModelProvider service. Implement a diagram.

**Comment by amolenaar** [comment]
To get minimal SysML support in:

- [ ] Create Block item
- [ ] Grouping for blocks (Inner blocks)
- [ ] Requirements palette. Which items should be in there?

@danyeaw Can you update this comment?

**Comment by amolenaar** [comment]
@danyeaw Thanks for the update. Which of the above need to be grouped in a diagram?

I suppose we need connectors for:
* block -> association
* block -> generalization
* port -> connector

Anything else?

**Comment by danyeaw** [comment]
The proxy ports are added to part or reference properties. You can use a connector between proxy ports, but also between the part/reference properties themselves.

- Trace, refine, verify, and satisfy relationships are allowed between a requirement and any other model element. The requirement is always at the head end.
- Derive is only allowed between two requirements

I think we are also going to need to customize the element editor, especially for a Requirement so that we can edit the requirement text, rationale, etc.

**Comment by danyeaw** [comment]
One additional thing that I think we need to support, it is common for the Name field of a Requirement to have multiple words as a summary of the requirement like `Maximum Vehicle Speed for Enable Condition`, and then the Text field will contain the full requirement text. In order to support this, I think our `Text` class in the diagram/shapes module and the definitions in the diagram/text module need to support word wrapping. Otherwise you get very wide requirements that can't be resized.

- [ ] Support Requirement Name text wrapping

**Comment by danyeaw** [comment]
The main part of the implementation still missing is for Internal Block Diagrams.

The look of an internal block diagram looks very similar to the component diagram that we currently support.

The main thing we need to be able to model are Part Properties and Reference Properties, and then be able to hook them up with connectors. Proxy ports are also an important addition. The SysML data model doesn't define unique elements for these properties, which makes implementation of this part somewhat unique. In SysML navigation is equivalent to a named property owned directly by a block.
- Part Property is the Composite Aggregation on a Block and displayed as a black diamond on an association. On an internal block diagram, this is shown as a rectangle with a solid outline, similar to a component.
- Reference Property is a property typed by a block without Composite Aggregation and normally this would be Shared Aggregation. Shared aggregation would displayed as a white diamond on an association. On an internal block diagram, this is shown as a rectangle with a dashed outline.

**Comment by amolenaar** [comment]
I can add Part/Reference properties.

**Comment by amolenaar** [comment]
Should proxy ports and connectors be exposed as two separate diagram items? Or should there be just a "Connector" with two fancy ports on its ends?

**Comment by danyeaw** [comment]
I think these should stay separate, but I do like the thought since we should try to keep things as simple and easy as possible.

- A connector can be between two part and/or reference properties directly, with no proxy ports used
- Proxy ports can be nested in each other to create a bus with pins
- Mutliple connectors can attach to a single proxy port

In the future we can also add types to a proxy port with a Block or Interface Block to enforce compatible information is sent between ports and over connectors.

**Comment by danyeaw** [comment]
Here are some things outstanding for SysML Support:
- Reference properties need to be shown on a diagram as a box with a dashed outline.
- Proxy ports are placed on the edge of part and reference properties.
- Connectors provide connections between proxy ports and/or part and reference properties.

### TODO
- [ ] Change properties to dashed lines if they are reference properties
- [ ] Create new IBD connector type that only connects between proxy ports and reference / part properties
- [ ] Update icons in the namespace so that reference and part properties are differentiated
- [ ] Add ProxyPortItem and represent them as a port on the edge on a part or reference property

**Comment by amolenaar** [comment]
> Change properties to dashed lines if they are reference properties

How do I know a property is a reference? Do we need a connector first?

**Comment by amolenaar** [comment]
> Add ProxyPortItem and represent them as a port on the edge on a part or reference property

To implement a ProxyPort right, we also need an InterfaceBlock it seems, according to the specs at least. The InterfaceBlock can not be related to the port in the diagram directly. I think this should be changed in the element editor.

**Comment by danyeaw** [comment]
> How do I know a property is a reference? Do we need a connector first?

Normally an Internal Block Diagram is a view inside of a block, so then if you add a property to the diagram you know if it part of the block or not. Since Gaphor doesn't have custom diagram types, maybe we should only create a reference property as a dashed line if you drag the property from the namespace nested under a block where it is a reference property for that block. 

> With the connector you mean the line with the equal sign?

Yes, those are the connectors. I am not sure why they have an equal sign in that diagram, I have never seen that before.

> To implement a ProxyPort right, we also need an InterfaceBlock it seems, according to the specs at least. The InterfaceBlock can not be related to the port in the diagram directly. I think this should be changed in the element editor.

The interface block is needed to add a type to a port, I think this could be a follow-up PR. The minimum we need is to be able to create a proxy port, give it a name, and attach it using a connector.

**Comment by amolenaar** [comment]
> > How do I know a property is a reference? Do we need a connector first?
> 
> Normally an Internal Block Diagram is a view inside of a block, so then if you add a property to the diagram you know if it part of the block or not. Since Gaphor doesn't have custom diagram types, maybe we should only create a reference property as a dashed line if you drag the property from the namespace nested under a block where it is a reference property for that block.

We can use Gaphor's grouping feature to allow a property to be placed inside a Block physically.

> > With the connector you mean the line with the equal sign?
> 
> Yes, those are the connectors. I am not sure why they have an equal sign in that diagram, I have never seen that before.

We can leave those out. Or keep them in if it makes things more clear.

> > To implement a ProxyPort right, we also need an InterfaceBlock it seems, according to the specs at least. The InterfaceBlock can not be related to the port in the diagram directly. I think this should be changed in the element editor.
> 
> The interface block is needed to add a type to a port, I think this could be a follow-up PR. The minimum we need is to be able to create a proxy port, give it a name, and attach it using a connector.

That's okay. When I connect a proxy port to a block, the port is added to the namespace of the block. The connector links to the port, although I have not figured out what connection should be made on model level, yet (can probably find that in the UML spec).

**Comment by danyeaw** [comment]
Although you can put a proxy port on a block, the normal use case is to put them on part or reference properties themselves.

**Comment by amolenaar** [comment]
Port:

![image](https://user-images.githubusercontent.com/96249/84437270-ffe9a300-ac34-11ea-8dd5-0b34dee9842c.png)

Still needs:
- [ ] Connector to block (should also raise the port's z-index
- [ ] Name
- [ ] Stereotype
- [ ] Orientation of text should change, depending on the side of the Block it's connected to

**Comment by amolenaar** [comment]
In this diagram

![img](https://user-images.githubusercontent.com/10014976/82839744-61bcb580-9e9e-11ea-85f6-df43a169b4b7.png)

_air_ is a `ConnectorEnd`, right? Since both _v_ and _tpms_ represent properties.

**Comment by amolenaar** [comment]
@danyeaw Can we close this issue?

**Comment by danyeaw** [comment]
@amolenaar I would like to model a simple system this weekend (air compressor) to test everything out, if I don't find any major issues then I think we can close this :+1:

**Comment by danyeaw** [comment]
I think we can go ahead a close this, congrats on the SysML-Lite support! :tada:
