### ISSUE TITLE
Use GTK 4 

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#618]
Gaphor is running on GTK+ 3, currently.

There are a couple of improvements in GTK 4 that make an (early?) migration an option, IMHO:

* Better cross platform support: a lot has been done to improve interoperability with Windows and macOS. I assume GTK4 will run smoother on those platforms.
* Better support for copy-and-paste: we can purely rely on GTK API's.
* More and better event controllers. Event controllers were backported from GTK 4 to GTK+ 3.

During migration we should still support GTK+ 3.

What we need before migrating:

- [x] Good availability of GTK 4 on the latest linux platforms (Arch :heavy_check_mark:, Ubuntu :heavy_check_mark: , Fedora :heavy_check_mark: ).
- [x] [PyGObject](https://gitlab.gnome.org/GNOME/pygobject) should be ready (works with master)
- [x] A GTK 4 base in Flatpak.
- [x] A GTK 4 package in MSys.
- [x] A GTK 4 package in Homebrew.
- [X] gtk-mac-integration? Still needed for GTK integration on macOS? _RESOLVED_: looks like [GTK can handle it by itself](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkapplication-quartz.c#L108).

What needs changing:

- [x] The tool bar should be rebuild using `Gtk.Expander` and `Gtk.FlowBox` (affects #498).
- [x] Event controllers are instantiated differently
- [x] See the migration guide: https://developer.gnome.org/gtk4/stable/gtk-migrating-3-to-4.html.
- [x] Implement Copy/paste - use `Gdk.Clipboard`. #274 
- [x] Implement DnD for Toolbox.
- [x] Toolbox: [Button remains in "pressed" state when used with GtkDragSource](https://gitlab.gnome.org/GNOME/gtk/-/issues/4416).
- [x] Fix issues with slow toolbox (`Gio.Action`), and recent files popup.
- [x] ~DnD is [not working for `Gtk.TreeView`](https://gitlab.gnome.org/GNOME/gtk/-/issues/3649) for GTK 4 ([see also](https://gitlab.gnome.org/GNOME/gtk/-/issues/3656)).~
- [x] Replace TreeView with a GTK4 [TreeListModel](https://docs.gtk.org/gtk4/class.TreeListModel.html) and [GtkTreeListRowSorter](https://docs.gtk.org/gtk4/class.TreeListRowSorter.html). The TreeView (still) has no DnD in GTK4 and we can [have better styling](https://blog.gtk.org/2020/06/07/scalable-lists-in-gtk-4/) with the new tree view logic. #1516 
- [x] Do TreeView is property pages need to be replaced too? Attributes and Operations can be reordered, which is currently not possible. _No, we currently do not support DnD in those tree views, so their behavior is fine.
- [ ] Update packaging on Linux (Flatpak), Windows and macOS. Can we still support AppImage?
- [x] Port Error Reports to GTK4
- [x] #1555 

Windows:

- [ ] gvsbuild for GTK4

macOS:

- [ ] DnD is [not working on macOS](https://gitlab.gnome.org/GNOME/gtk/-/issues/3423) for GTK 4 ([fix](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4523)).
- [x] Application window placement is [partly off-screen on macOS](https://gitlab.gnome.org/GNOME/gtk/-/issues/3821) for GTK 4.

Open issues:

- [x] Warning `(gaphor:1404167): Gtk-CRITICAL **: 09:20:44.145: gtk_event_controller_get_propagation_phase: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed`. Why is this here? What controller does it refer to?
- [x] `Help` items in property editor do not work (fixed by 40e290b0dc2e83bb39ceee572615eda6d323ed20)
- [x] Save changes dialog (when exiting app) is not modal to the window (can still edit model) (fixed by 4aa161b0e8489850e85407f0c5b921bd45670eff)
- [x] Console message `Unsupported modifier, resource creation failed. XXX: resource creation failed`. Solved. It's a Mesa/Wayland issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6643
- [x] Console window is only 3 lines high.

**Comment by amolenaar** [comment]
At this point all tests pass with GTK 4.0.3. Tests fail with GTK >= 4.1.0 due to a change in the `Gtk.ListStore` bindings. A fix for PyGObject is to be merged.

One issue I can't seem to nail down is why it takes so long to populate the recent files popup, as well as the toolbar actions (tested on GTK 4.0.3 and 4.2.1).

**Comment by amolenaar** [comment]
Needs resolution for:

* PR https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/175
* PR https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/172
* Issue https://gitlab.gnome.org/GNOME/gtk/-/issues/3656

**Comment by danyeaw** [comment]
Nice contributions @amolenaar! I gave them all a thumbs up on GitLab

**Comment by amolenaar** [comment]
I'll close this issue. We have GTK4 support for Linux (Flatpak). Windows and macOS need upstream fixes for GTK4. I'm not sure if GTK4 to ever work for AppImage.
